### PR TITLE
adding 2 lines makes micromustache easily extendable (+test)

### PR DESCRIPTION
**Pull request by coderofsalvation**
In order to make functions powerful, one needs arguments.

Words of praise: I really love micromustache as my go-to template engine, its lightweight and works in both browser and nodejs.
However, I found myself jumping thru a lot of hoops, ending up with a lot of functions.
These two lines would fix that problem.

usecases are infinite: https://gist.github.com/coderofsalvation/93610d527c7b8534567f

Please merge this, as I think this could really be the last tweak to this module (does one need more than functions and arguments? I dont think so).
If not, also ok (then I'll publish it as micromustache++ or something )

### CODE REVIEW

**Comment by userpixel** [comment]
@coderofsalvation is this behaviour compatible with Mustache?

**Comment by coderofsalvation** [comment]
yes and no.
A major flaw in mustache is that arguments cannot be passed into functions (except the current variablename).
Therefore, mustache tests would not fail simply because there are no tests for it :)
It is safe to say that this won't hurt.

**Comment by coderofsalvation** [comment]
100% Yes.
 
First of all mustache tests would not fail simply because there are no tests for multiple argument functions :)
Second, mustache behaviour is first choice.
So for example {{foo:one:two}} would resolve like this:

## mustache 
1. tries to return view['foo:one:two']
2. tries to return view['foo:one:two']()

## micromustache
1. tries to return view['foo:one:two']
2. tries to return view['foo:one:two']()
3. tries to return view['foo']
4. tries to return view['foo']("one","two")

It is safe to say that this is harmless.

**Comment by coderofsalvation** [comment]
100% Yes, doublechecked that.
 
First of all mustache tests would not fail simply because there are no tests for multiple argument functions :)
Second, micromustache will always prioritize mustache behaviour.
For example, let assume the highly unlikely case where users use semicolons in variables.
Then `{{foo:one:two}}` would resolve like this:

## mustache 
    1. tries to return view['foo:one:two']
    2. tries to return view['foo:one:two']()
    3. return ""

## micromustache
    1. tries to return view['foo:one:two']
    2. tries to return view['foo:one:two']()
    3. tries to return view['foo']
    4. tries to return view['foo']("one","two")
    5. return ""

All tests (including 3+4) work. It is safe to say that this is harmless.

**Comment by userpixel** [comment]
Sounds interesting. I have to do some performance tests since the main selling point of micromustache is achieving speed by eliminating not-so-commonly-used features of mustache. I will get back to you.

**Comment by coderofsalvation** [comment]
what are you using to test this?

**Comment by userpixel** [comment]
https://jsperf.com/

Do you mind creating a performance test comparing the current MicroMustache with your version? If it's faster (I'll merge directly).

**Comment by coderofsalvation** [comment]
Thx for your message.
I can already tell you (without jsperf) that adding a split() won't make things faster.
Anyways, don't bother.
I've decided to part with the idea of moving forward with micromustache, as I've come to understand the main goal of micromustache is not perse extendability (but rather speed and mustache compatibility).
This is totally fine by me, however, I found myself longing for a new flavor of mustache with more extendability and less noise.
For example:

     {{#foo}} {{/foo}} {{^foo}}  {{/foo}}

Will this loop thru an array? Or just an if-expression?
The statement above is confusing to say the least.

I'd rather have {{if:foo:foo:somethingelse}} and {{each:foo:footemplate}} using the split()-feature.
Hence I created this, and will move forward with this:

https://www.npmjs.com/package/brown
https://www.npmjs.com/package/brown-ext-basic
https://www.npmjs.com/package/brown-express

Cheers

**Pull request closed without merging**
